export const filterValues = new Map<string, Array<string | number>>([
  [
    "Year",
    [
      "2020`s",
      "2010`s",
      "2000`s",
      "1990`s",
      "1980`s",
      "1970`s",
      "1960`s",
      "1950`s",
      "1940`s",
      "1930`s",
      "1920`s",
      "1910`s",
      "1900`s",
      "1890`s",
    ],
  ],
  [
    "Rating",
    [
      "0 / 10",
      "1 / 10",
      "2 / 10",
      "3 / 10",
      "4 / 10",
      "5 / 10",
      "6 / 10",
      "7 / 10",
      "8 / 10",
      "9 / 10",
      "10 / 10",
    ],
  ],
  [
    "Genre",
    [
      "Action",
      "Adventure",
      "Animation",
      "Crime",
      "Documentary",
      "Drama",
      "Family",
      "Fantasy",
      "History",
      "Horror",
      "Music",
      "Mystery",
      "Romance",
      "Sci-Fi",
      "Thriller",
      "War",
      "Western",
    ],
  ],
]);

export const sortValues = [
  "Most Popular First",
  "Least Popular First",
  "Newest First",
  "Oldest First",
  "Film Name A-Z",
  "Film Name Z-A",
  "Rating Highest First",
  "Rating Lowest First",
  "Longest First",
  "Shortest First",
];

export const headerProfileValues = [
  "Profile",
  "My Films",
  "Diary",
  "Watchlist",
  "Settings",
];
